# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            iknuth.com
tagline:          Edwin Knuth
url:              http://eknuth.github.io/iknuth.com
paginate:         1
baseurl:          /iknuth.com/
author:
  name:           Edwin Knuth
  url:            http://iknuth.com
  email:          eknuth@gmail.com

# Custom vars
version:          1.0.0
github:			  eknuth
repo:           https://github.com/eknuth/eknuth.github.com
